font_size 18.0
background_opacity 0.8
#include neofusion.kitty/neofusion.conf

# tabs
tab_bar_edge top
tab_bar_align center
tab_bar_style powerline
tab_powerline_style slanted

# tabs colors
active_tab_foreground #070f1c
active_tab_background #ea6847
# or cyan: active_tab_background #86dbf5
inactive_tab_foreground #22536f 
inactive_tab_background #070f1c
